---
abstract: 'Generate JUnit compatible output from TAP results'
author:
  - 'Lubomir Rintel (GoodData) <lubo.rintel@gooddata.com>'
build_requires:
  Test::Deep: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Harness-JUnit
provides:
  TAP::Harness::JUnit:
    file: lib/TAP/Harness/JUnit.pm
    version: 0.36
  TAP::Harness::JUnit::Parser:
    file: lib/TAP/Harness/JUnit.pm
requires:
  Encode: 0
  File::Temp: 0
  Scalar::Util: 0
  TAP::Harness: 3.05
  TAP::Parser: 0
  Test::More: 0
  XML::Simple: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=TAP-Harness-JUnit
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jlavallee/tap-harness-junit
version: 0.36
